import { JSDOM } from "jsdom";
import fs from "fs";
const html = fs.readFileSync(new URL("./renderer/index.html","file://"+process.cwd()+"/"),"utf8");
const dom = new JSDOM(html, { runScripts: "outside-only", url: "https://x.test/" });
globalThis.window = dom.window; globalThis.document = dom.window.document;
globalThis.localStorage = dom.window.localStorage;   // global in Electron
let mermaidCalls=[];
dom.window.mermaid={ initialize:()=>{}, render: async (id,code)=>{ mermaidCalls.push(code); return {svg:`<svg data-id="${id}">DIAGRAM</svg>`}; } };
let eventCb=()=>{}; const sent=[];
dom.window.api={ onServeEvent:cb=>{eventCb=cb}, onServeLog:()=>{}, sendRequest:r=>sent.push(r), openFigure:async()=>"" };
globalThis.window.api=dom.window.api;
await import("./dist/renderer.js");
eventCb({type:"ready",docs:["A.pdf"],chunks:5,vision_model:"gpt-4o",embed_model:"x"});
document.getElementById("input").value="explain";
document.getElementById("send").click();
const reqId=sent[sent.length-1].reqId;
const md="## Result\n\nGain is **30 dB** = `20*log10(31.6)`.\n\n- one\n- two\n\n```python\nx=2+2\n```\n\n```mermaid\ngraph TD; A-->B;\n```\n\nSee (A.pdf p.5).";
eventCb({type:"answer",reqId,text:md,thinking:"",sources:[{doc:"A.pdf",page:5,image:"/idx/p5.png"}],usage:{prompt:10,completion:5,total:15}});
await new Promise(r=>setTimeout(r,40));
const h=document.getElementById("messages").innerHTML;
const ok=(n,c)=>console.log((c?"PASS":"FAIL"),n);
ok("heading",/<h2>Result<\/h2>/.test(h));
ok("bold",/<strong>30 dB<\/strong>/.test(h));
ok("inline code",/<code>20\*log10/.test(h));
ok("list",/<ul>[\s\S]*<li>one<\/li>/.test(h));
ok("code block",/<pre><code>x=2\+2<\/code><\/pre>/.test(h));
ok("mermaid -> svg",/<svg data-id="mmd\d+">DIAGRAM<\/svg>/.test(h));
ok("mermaid code passed",mermaidCalls.length===1 && /graph TD/.test(mermaidCalls[0]));
ok("citation link",/a class="fig" data-img="\/idx\/p5.png"/.test(h));
ok("token stats",/session: 15 tok/.test(document.getElementById("token-stats").textContent));
const saved=localStorage.getItem("pdf_qa_threads_v1");
ok("persisted with content",!!saved && /explain/.test(saved) && /30 dB/.test(saved));
