import { JSDOM } from "jsdom"; import fs from "fs";
const html = fs.readFileSync(new URL("./renderer/index.html","file://"+process.cwd()+"/"),"utf8");
const dom = new JSDOM(html,{runScripts:"outside-only",url:"https://x.test/"});
globalThis.window=dom.window; globalThis.document=dom.window.document; globalThis.localStorage=dom.window.localStorage;
const mathSeen=[];
dom.window.katex={ renderToString:(tex,opts)=>{ mathSeen.push({tex,display:opts.displayMode}); return `<span class="katex" data-d="${opts.displayMode}">RENDERED</span>`; } };
dom.window.mermaid={initialize:()=>{},render:async()=>({svg:""})};
let cb=()=>{}; const sent=[];
dom.window.api={onServeEvent:c=>{cb=c},onServeLog:()=>{},sendRequest:r=>sent.push(r),openFigure:async()=>""};
globalThis.window.api=dom.window.api;
await import("./dist/renderer.js");
cb({type:"ready",docs:["A.pdf"],chunks:1,vision_model:"gpt-4o",embed_model:"x"});
document.getElementById("input").value="formula?"; document.getElementById("send").click();
const reqId=sent[sent.length-1].reqId;
const md="The formula is:\n\n\\[ P_{out} = \\frac{10^{(SPL-SPL_{ref})/10}}{S} \\]\n\nInline \\(x^2\\) and $y=2$ too.";
cb({type:"answer",reqId,text:md,thinking:"",sources:[],usage:{prompt:1,completion:1,total:2}});
await new Promise(r=>setTimeout(r,20));
const h=document.getElementById("messages").innerHTML;
const ok=(n,c)=>console.log(c?"PASS":"FAIL",n);
ok("display math rendered",/<span class="katex" data-d="true">RENDERED<\/span>/.test(h));
ok("inline math rendered",/<span class="katex" data-d="false">RENDERED<\/span>/.test(h));
ok("captured display latex",mathSeen.some(m=>m.display&&/P_\{out\}/.test(m.tex)));
ok("captured inline x^2",mathSeen.some(m=>!m.display&&/x\^2/.test(m.tex)));
ok("captured $ inline",mathSeen.some(m=>/y=2/.test(m.tex)));
ok("count = 4",mathSeen.length===4);
